{
 "title": "Monitoring: testground-base",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage: namespace: testground-base",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (pod)(rate(container_cpu_user_seconds_total{\n  namespace=\"testground-base\"\n}[5m]))"
    }
   ]
  },
  {
   "title": "Memory usage: namespace: testground-base",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(max by (pod)(max_over_time(container_memory_usage_bytes{\n  namespace=\"testground-base\",\n}[5m]))/ on (pod) (max by (pod) (kube_pod_container_resource_limits)) * 100,0.01)"
    }
   ]
  },
  {
   "title": "CPU usage in Consensus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{\n  namespace=\"testground-base\",\n  pod=~\"consensus.+\",\n  container=\"consensus\",\n}[5m])"
    }
   ]
  },
  {
   "title": "CPU usage in Consensus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{\n  namespace=\"testground-base\",\n  pod=~\"consensus.+\",\n  container=\"consensus\",\n}[5m])"
    }
   ]
  },
  {
   "title": "Memory usage in Consensus",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(max by (pod)(max_over_time(container_memory_usage_bytes{\n  namespace=\"testground-base\",\n  pod=~\"consensus.+\",\n  container=\"consensus\",\n}[5m]))/ on (pod) (max by (pod) (kube_pod_container_resource_limits)) * 100,0.01)"
    }
   ]
  },
  {
   "title": "Memory usage in DA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(max by (pod)(max_over_time(container_memory_usage_bytes{\n  namespace=\"testground-base\",\n  pod=~\"da.+\",\n  container=\"da\",\n}[5m]))/ on (pod) (max by (pod) (kube_pod_container_resource_limits)) * 100,0.01)"
    }
   ]
  },
  {
   "title": "K8S Memory Nodes Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (\n  instance:node_memory_utilisation:ratio\n)"
    }
   ]
  },
  {
   "title": "K8S CPU Nodes Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (\n  instance:node_cpu_utilisation:rate5m\n)"
    }
   ]
  }
 ]
}