{
 "title": "Logs: testground-base",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "testground-base - NameSpace - Number of msg",
   "type": "graph",
   "description": "Number of messages in the namespace",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({namespace=\"testground-base\"}[$__interval])"
    }
   ]
  },
  { "title": "testground - Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "testground-base-consensus - NameSpace",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=~\"testground-base\"}"
    }
   ]
  },
  {
   "title": "testground-base-consensus - Full",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{app=~\"consensus-full-*.\",namespace=\"testground-base\"}"
    }
   ]
  },
  {
   "title": "testground-base-consensus - Validator",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{app=~\"consensus-validator-*.\",namespace=\"testground-base\"}"
    }
   ]
  },
  { "title": "testground - Data Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "testground-base-da - NameSpace - Number of msg",
   "type": "graph",
   "description": "Number of messages in the namespace",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({namespace=\"testground-base\"}[$__interval])"
    }
   ]
  },
  {
   "title": "testground-base-da - Errors in the Namespace",
   "type": "logs",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{namespace=\"testground-base\"}|=\"ERROR\""
    }
   ]
  },
  {
   "title": "testground-base-da - Errors in the Namespace",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"testground-base\"}|=\"ERROR\"[5m]))"
    }
   ]
  },
  {
   "title": "testground-base-da - NameSpace",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{namespace=\"testground-base\"}"
    }
   ]
  },
  {
   "title": "testground-base-da - Bridge-1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "{app=~\"da-bridge-1\",namespace=\"testground-base\"}"
    }
   ]
  },
  {
   "title": "testground-base-da - Bridge-2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "{app=~\"da-bridge-2\",namespace=\"testground-base\"}"
    }
   ]
  },
  {
   "title": "testground-base-da - Full-1",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{app=~\"da-full-1\",namespace=\"testground-base\"}"
    }
   ]
  },
  {
   "title": "testground-base-da - Full-2",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "{app=\"da-full\",namespace=\"testground-base\"}"
    }
   ]
  },
  {
   "title": "external-dns",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "{app=\"external-dns\",namespace=\"testground-base\"}"
    }
   ]
  }
 ]
}