---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-csi-controller-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: efs-csi-controller-sa
rules:
- apiGroups: [""]
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups: ["coordination.k8s.io" ]
  resources: ["leases"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-csi-controller-sa-rolebinding
subjects:
- kind: ServiceAccount
  name: efs-csi-controller-sa
roleRef:
  kind: Role
  name: efs-csi-controller-sa
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: efs-csi-controller-sa-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - get
    - list
    - create
    - delete
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: efs-csi-controller-sa-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: efs-csi-controller-sa-cluster-role
subjects:
- kind: ServiceAccount
  name: efs-csi-controller-sa
