apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: softlink-cm
  name: softlink-cm
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: softlink-cm
  template:
    metadata:
      labels:
        k8s-app: softlink-cm
    spec:
      initContainers:
      - image: amazonlinux
        imagePullPolicy: Always
        name: softlink-cm
        command: ["/scripts/softlink-cm.sh"]
        securityContext:
          allowPrivilegeEscalation: true
        volumeMounts:
        - mountPath: /tmp
          name: output
        - mountPath: /etc/cron.d
          name: cron
        - name: softlink-cm
          mountPath: /scripts
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: output
        hostPath:
          path: /tmp
          type: Directory
      - name: cron
        hostPath:
          path: /etc/cron.d
          type: Directory
      - name: softlink-cm
        configMap:
          name: softlink-cm
          defaultMode: 0744
      containers:
        - image: "gcr.io/google-containers/pause:2.0"
          name: pause
