apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy
  namespace: default
  labels:
    k8s-app: dummy
spec:
  selector:
    matchLabels:
      name: dummy
  template:
    metadata:
      labels:
        name: dummy
    spec:
      priorityClassName: system-node-critical
      volumes:
      - name: host-sys
        hostPath:
          path: /sys
      containers:
      - name: dummy
        command: ["/bin/sleep", "3650d"]
        image: iptestground/curl-ssl:0.0.1
        resources:
          requests:
            cpu: 100m
            memory: 10Mi
