controller:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  nodeSelector:
    testground.node.role.infra: "true"

defaultBackend:
  nodeSelector:
    testground.node.role.infra: "true"
