kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testground-daemon-datadir-pvc
  labels:
    type: aws-ebs
spec:
  storageClassName: "gp2-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
