apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: promtail
  releaseName: grafana-promtail
  repo: https://grafana.github.io/helm-charts
  version: "6.9.3"
  valuesFile: values.yaml
  namespace: default
