apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      influxdb:
        endpoint: http://influxdb:8086
        timeout: 500ms
        org: default
        bucket: testground
        metrics_schema: telegraf-prometheus-v1

        sending_queue:
          enabled: true
          num_consumers: 3
          queue_size: 10

        retry_on_failure:
          enabled: true
          initial_interval: 1s
          max_interval: 3s
          max_elapsed_time: 10s
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [influxdb]
