apiVersion: v1
kind: Service
metadata:
  name: testground-sync-service
  labels:
    name: testground-sync-service
spec:
  ports:
  - port: 5050
    protocol: TCP
  selector:
    name: testground-sync-service