# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: testground-tools-telegraf-operator
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: telegraf-operator
#     repoURL: https://helm.influxdata.com/
#     targetRevision: 1.3.11
#     helm:
#       releaseName: telegraf-operator
#       values: |
#         replicaCount: 2
#         classes:
#           data:
#             default: |
#               [[outputs.influxdb]]
#                 urls = ["http://influxdb:8086"]
#                 database = "testground"
#         resources:
#           limits:
#             cpu: 400m
#             memory: 256Mi
#           requests:
#             cpu: 50m
#             memory: 64Mi
#         hotReload: true
#   destination:
#     namespace: default
#     name: in-cluster
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: true
#     syncOptions:
#       - ApplyOutOfSyncOnly=true
#       - CreateNamespace=true
#       - ServerSideApply=true
