apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: telegraf-operator
  releaseName: telegraf-operator
  repo: https://helm.influxdata.com/
  version: 1.3.11
  valuesFile: values.yaml
  namespace: default

# resources:
#   - argocd_app.yaml
