apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  config:
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
  - matchExpressions:
    - { key: app, operator: In, values: [ grafana ] }
  resources:
    # Optionally specify container resources
    requests:
      cpu: 800m
      memory: 400Mi
    limits:
      memory: 800Mi
