apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testground
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/testground/infra.git
      revision: v0.7.0
      directories:
      - path: 'manifests/testground/*'
      - path: manifests/testground/deactivated
        exclude: true
  template:
    metadata:
      name: 'testground-{{path[2]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/testground/infra.git
        path: 'manifests/testground/{{path[2]}}'
        targetRevision: v0.7.0
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - ServerSideApply=true
