{
 "title": "WeaveNet",
 "description": "WeaveNet metrics. It was made on top of the weavenet prometheus metrics. Please check this for more details https://www.weave.works/docs/net/latest/tasks/manage/metrics",
 "tags": [ "practo-managed" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_cpu_seconds_total, cluster)"
   },
   { "name": "interval", "query": "4h" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(weave_ipam_unreachable_percentage, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fast DP Flows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_flows{instance=\"$instance\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "IPAM Pending Allocates",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_ipam_pending_allocates{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "IPAM Pending Claims",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_ipam_pending_claims{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max IPs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(label_replace(weave_max_ips{instance=\"$instance\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "Terminations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "cpm",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(weave_connection_terminations_total{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "P2P Established",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"established\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "P2P Connecting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"connecting\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "P2P Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"pending\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "P2P Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"failed\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))"
    }
   ]
  },
  {
   "title": "P2P Retrying",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"retrying\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))"
    }
   ]
  },
  { "title": "IPAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "IPAM Unreachable Percentage",
   "type": "graph",
   "description": "Percentage of all IP addresses owned by unreachable peers.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(weave_ipam_unreachable_percentage{instance=\"$instance\"}, \"node\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "IPAM unreachable percentage"
    }
   ]
  },
  {
   "title": "IPAM Unreachable Count",
   "type": "graph",
   "description": "Number of unreachable peers that own IPAM addresses.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(weave_ipam_unreachable_count{instance=\"$instance\"}, \"node\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "IPAM unreachable count"
    }
   ]
  },
  {
   "title": "IPAM Pending",
   "type": "graph",
   "description": " Number of pending allocates and claims.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(weave_ipam_pending_allocates{instance=\"$instance\"}, \"node\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "pending allocates"
    },
    {
     "expr": "label_replace(weave_ipam_pending_claims{instance=\"$instance\"}, \"node\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "pending claims"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Fast DP Flows",
   "type": "graph",
   "description": "https://github.com/weaveworks/weave/blob/master/site/concepts/fastdp-how-it-works.md",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(weave_flows{instance=\"$instance\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "weave fast dp flows"
    }
   ]
  },
  {
   "title": "Rate of Terminated Connections",
   "type": "graph",
   "description": "https://weave-community.slack.com/archives/C2ND76PAA/p1582641797016700?thread_ts=1582613239.010900&cid=C2ND76PAA",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "label_replace(increase(weave_connection_terminations_total{instance=\"$instance\"}[1m]), \"node\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "rate of terminated connections"
    }
   ]
  },
  {
   "title": "P2P / Established",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"established\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "connections established"
    }
   ]
  },
  {
   "title": "P2P / Connecting",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"connecting\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "connections connecting"
    }
   ]
  },
  {
   "title": "P2P / Pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"pending\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "connections pending"
    }
   ]
  },
  {
   "title": "P2P / Retrying",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"retrying\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "retrying connections"
    }
   ]
  },
  {
   "title": "P2P / Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{instance=\"$instance\", state=\"failed\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "failed connections"
    }
   ]
  }
 ]
}