auth:
  enabled: false
influxdb:
  nodeSelector:
    testground.node.role.infra: "true"
  service:
    type: ClusterIP
    clusterIP: None
  initdbScripts:
    create_database.txt: |-
      CREATE DATABASE testground;