apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ./base
  - dashboards.yaml

configMapGenerator:
  - name: testground
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/base-logs.json
      - dashboards/base-monitoring.json
