testground-ami-images:
	packer build -var 'source_ami=ami-093dda5e01f6102a8' -var 'aws_region=eu-central-1'   testground-ami.json
	packer build -var 'source_ami=ami-05516775460f4eb85' -var 'aws_region=eu-west-2'      testground-ami.json
	packer build -var 'source_ami=ami-09e51e3726d58e07a' -var 'aws_region=eu-west-1'      testground-ami.json
	packer build -var 'source_ami=ami-06b06b52eb579522b' -var 'aws_region=us-east-1'      testground-ami.json
	packer build -var 'source_ami=ami-075dbb5513cc94405' -var 'aws_region=us-east-2'      testground-ami.json
	packer build -var 'source_ami=ami-00ad1aa0da4d6f24b' -var 'aws_region=us-west-1'      testground-ami.json
	packer build -var 'source_ami=ami-020f0cd7f47563ce3' -var 'aws_region=us-west-2'      testground-ami.json
	packer build -var 'source_ami=ami-07dd82a6859b4a2ed' -var 'aws_region=ap-southeast-1' testground-ami.json
